# Generated by Django 4.0.6 on 2022-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CmdCenterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(max_length=500),
        ),
    ]
